### PR TITLE
Create ehicks8.md

### PR DESCRIPTION
**Pull request by EthanHicks1**

### CODE REVIEW

**Comment by 3PIV** [comment]
Hi Ethan! Could you add your public key to this commit?

**Comment by EthanHicks1** [comment]
What is this `list.txt` file that the directions are referring to in step 3 of PuTTY directions?

**Comment by audrism** [comment]
Fixed the text: it is yournetid.key file

**Comment by EthanHicks1** [comment]
Ok. Thanks. I now have added my id and public key in my `netid.key` file.

**Pull request merged**
